### PR TITLE
Fix waypoint arrival issue.

### LINKED ISSUE #63: Waypoint Arrival Screen example doesn't continue after arrival to first waypoint
In Waypoint Arrival Screen example after arrival to first waypoint alert is shown, after accepting it and incrementing `legIndex` trip doesn't continue. It's also not possible to dismiss `NavigationViewController` and restart trip.

### PR DESCRIPTION
**Pull request by MaximAlien**
Fixes #63.

### CODE REVIEW

File: Navigation-Examples/Examples/Waypoint-Arrival-Screen.swift [hunk 1]
```diff
@@ -40,13 +40,25 @@ class WaypointArrivalScreenViewController: UIViewController {
...
+        let isFinalLeg = navigationViewController.navigationService.routeProgress.isFinalLeg
+        if isFinalLeg {
+            return true
+        }
+        
+        let alert = UIAlertController(title: "Arrived at \(waypoint.name ?? "Unknown").", message: "Would you like to continue?", preferredStyle: .alert)
         alert.addAction(UIAlertAction(title: "Ok", style: .default, handler: { action in
             // Begin the next leg once the driver confirms
-            navigationViewController.navigationService.routeProgress.legIndex += 1
+            if !isFinalLeg {
```
Comment (dersim-davaod) [inline Navigation-Examples/Examples/Waypoint-Arrival-Screen.swift:51]: nit: do we need this explicit check taking into account the check above?

Comment (MaximAlien) [reply Navigation-Examples/Examples/Waypoint-Arrival-Screen.swift:51]: Yes, check is required since additional logic is being triggered after setting `legIndex` (including assert which checks whether we're in correct range).

File: Navigation-Examples/Examples/Waypoint-Arrival-Screen.swift [hunk 2]
```diff
@@ -40,13 +40,25 @@ class WaypointArrivalScreenViewController: UIViewController {
 extension WaypointArrivalScreenViewController: NavigationViewControllerDelegate {
     // Show an alert when arriving at the waypoint and wait until the user to start next leg.
     func navigationViewController(_ navigationViewController: NavigationViewController, didArriveAt waypoint: Waypoint) -> Bool {
-        let alert = UIAlertController(title: "Arrived at \(String(describing: waypoint.name))", message: "Would you like to continue?", preferredStyle: .alert)
+        let isFinalLeg = navigationViewController.navigationService.routeProgress.isFinalLeg
```
Comment (MaximAlien) [inline Navigation-Examples/Examples/Waypoint-Arrival-Screen.swift:43]: This check is needed to automatically end trip (without prompting user to interact with alert) in case if current leg is final.
